### ISSUE TITLE
Login via h5 and h5-ao via Firefox has issue on password entry

### ISSUE THREAD

**Issue by arjenlentz** [HeuristNetwork/heurist#20]
When entering the password from Firefox (63.0), the pwd field flickers and generally only stays at the first character, so you can't login. Looks like there is some Javascript actively interfering during the typing.
On Brave and Chrome browsers it's ok.

**Comment by arjenlentz** [comment]
These are the console errors that I see at that point.

unreachable code after return statement[Learn More] recordAction.js:292:16
unreachable code after return statement[Learn More] resultList.js:669:12
unreachable code after return statement[Learn More] expertnation_nav.js:475:40
unreachable code after return statement[Learn More] expertnation_nav.js:2529:8
unreachable code after return statement[Learn More] editing_input.js:1181:28
unreachable code after return statement[Learn More] resultList.js:669:12
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] h5-ao

**Comment by ijohnson222** [comment]
I suspect this was a temporary problem as I have not received any other report of this and cannot reproduce it myself. Also we no logner use an http server. Login appears fine. It might have something to do with specific screen resolution, you see similar jitters on a lot of web sites when adding a character causes it to reformat, but reformatted it doesn't need to be so it resets.
