### ISSUE TITLE
Google Analytics ID should be in config, not code

### ISSUE THREAD

**Issue by arjenlentz** [HeuristNetwork/heurist#21]
https://github.com/HeuristNetwork/heurist/blob/c1e98dc7c60ae4b6d5342a4dffecf76b58df9e22/index.php#L431

This line and a few onward refer to the Google Analytics ID, hard-coded. This means that installs elsewhere will pollute the analytics.
So this should be in the Heurist config, not the code.

**Comment by ijohnson222** [comment]
This is intentional because Heurist is a distributed network and we are interested in usage on all servers, not just on one server.
