### ISSUE TITLE
[Moved to JT] Improve layout of the XML/JSON import message about structure synchronisation

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#26]
Currently you see a "synch listed entity types" button on the screen, but do not see the Import Records button (it's off the bottom). The synch button may not be needed, better to put up top as shown. Make sure line spacing is right once you've moved it, try and avoid Import Records going off the page unless there is a very long list of entity types to match.

![image](https://user-images.githubusercontent.com/4169217/72763673-f4232300-3c38-11ea-99f5-dbd766d468b5.png)

**Comment by yangli0516** [comment]
Please confirm the screen above is produced by clicking "Import" -> "Heurist XML/Json".

Currently got an error when uploading a JSON file.
![image](https://user-images.githubusercontent.com/8685304/73995001-79cdff00-49ab-11ea-9de4-899f488d7c99.png)

**Comment by ijohnson222** [comment]
That's right, I get this with a JSON file using Import > XML/JSON

Ian Johnson | Honorary Associate
The University of Sydney
Faculty of Arts and Social Sciences
Rm 316, Old Teachers College A22 | The University of Sydney | NSW | 2006
35, rue des Abbesses, Paris 75018
Au +61 402 389 190 | Fr +33 6 95 34 14 66
E <mailto:firstname.surname@sydney.edu.au> ian.johnson@sydney.edu.au<mailto:ian.johnson@sydney.edu.au>  | HeuristNetwork.org<http://heuristnetwork.org/>  | <http://usyd.academia.edu.au/IanJohnson> sydney.academia.edu/Johnson<http://sydney.academia.edu/Johnson> | sydney.edu.au<http://sydney.edu.au/>
CRICOS 00026A. This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.


________________________________
