### ISSUE TITLE
[Moved to JT] Popup/in on results list: scale length of component to length of content

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#27]
Can the pop-in data view for the results list set its length to the length of the contents? Currently get huge blank (this is where it matters) or only see half the data (in the end, this isn't really a problem, after all iti s embedding itself in a list or a map, we don't necessarily want it taking up teh whole of the available space).
  
![image](https://user-images.githubusercontent.com/4169217/72764582-f5564f00-3c3c-11ea-9dbc-46c54e5dd49a.png)

![image](https://user-images.githubusercontent.com/4169217/72764584-fa1b0300-3c3c-11ea-9bc9-29a46e56b1b4.png)

**Comment by yangli0516** [comment]
Need find a auto-resize solution to fit the content height. However, for content longer than the screen height, the scroll bar is still needed.

**Comment by yangli0516** [comment]
At hclient\widgets\viewers\resultList.js line 1487, current dialog height is set to 800, or 20 px lesser than the page height if the screen is smaller. Will play with the JQuery UI dialog options.

**Comment by ijohnson222** [comment]
Actually, the real problem is not the limitation in height when the content is longer than the popup area, the real issue is a popup with a lot of empty space at the end. So fine to stick with max length 800 or page height les 20px, but if the content is much shorter it shoudl shrink to fit. I think this could be triggered after content load, with no action if the content is larger than the container.
