### ISSUE TITLE
Export XML/JSON: warning if follow all pointers checkbox is unchecked 

### ISSUE THREAD

**Issue by VincentSheehan** [HeuristNetwork/heurist#45]
If user 

- unchecks the follow all pointers checkbox, pop up a warning (because this can really generate stuffed-up data if they don't know what they are doing): 

**WARNING** 
You have chosen not to follow pointers. 
Record pointer fields in this set of records will NOT be exported.
The data for these records will therefore be incomplete. Use with caution.
[Proceed]     [Cancel]

**Comment by ijohnson222** [comment]
deprecated by new options
