### ISSUE TITLE
Improve layout of header section of dashboard

### ISSUE THREAD

**Issue by VincentSheehan** [HeuristNetwork/heurist#49]
Move dashboard into a 'ribbon' below heading
Reduce size of icons to 70% of current
Reduce spacing and maximum length of description so it all fits nicely as shown
New close and edit - make sure the close up/open down arrow is sufficiently bold as shown, not some tiny thing. No need for the temporary close button
Reverse arrow direction when closed to allow reopen. Remove the special [Dashboard] control in the page header - I think the up / down arrow is sufficient. 
Dashboard open for new databases. Once closed, dashboard should stay closed until reopened by user (ie. state is current "Don't show again")

![image](https://user-images.githubusercontent.com/4169217/74116602-71263480-4c08-11ea-8ec1-1c4791b33d63.png)

WAS: The dashboard really gets in the way once you are a user. It's really intended for starters. Change order of controls at top and wording of buttons to make it clearer how to get rid of it:

![image](https://user-images.githubusercontent.com/25578092/72823379-847a5b80-3c6b-11ea-8c41-729ee68a57bd.png)

**Comment by yangli0516** [comment]
Hi @VincentSheehan could you attach a more clear version of the image above. Currently it looks blurred to me.

**Comment by ijohnson222** [comment]
I will send a new layout in an jour. Slightly more challenging but better

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by ijohnson222** [comment]
New layout suggested as a 'ribbon' which can be opened/closed using conventional ribbon control. I hope the resolution is aderquate. Anyhting in purple is (always) jsut guidelines or notes

**Comment by ijohnson222** [comment]
Deprecated by version 6
