### ISSUE TITLE
Popu warning when user tries to export XML or JSon without following all pointers

### ISSUE THREAD

**Issue by VincentSheehan** [HeuristNetwork/heurist#52]
If user unchecks "follow all pointers" give them the following warning popup:

WARNING: by allowing the export of records without following pointers, you will lose any data which is referenced by pointer fields in the exported records. This may be acceptable for simple lists eg. of places or person names, but you need to understand the nature of the exported records to be sure that you are not losing essential data.
Exporting and importing a CSV file will give you more control on what fields are exported.
Are you sure?
							[ Proceed ]     [Cancel]

**Comment by ijohnson222** [comment]
Deprecated by imporved menu of choices
