### ISSUE TITLE
Improve wrapping in header of resutls list by moving list of pages to top line

### ISSUE THREAD

**Issue by VincentSheehan** [HeuristNetwork/heurist#56]
This ugly wrapping (top) occurs almost all the time if there are a few pages, even with short saved search title. Move display mode down to line with menu, shorten the display of multiple pages, so it stays on two lines except in exceptional circumstances.

![image](https://user-images.githubusercontent.com/25578092/72824070-93154280-3c6c-11ea-9085-ccb040820066.png)

**Comment by ijohnson222** [comment]
Deprecated by version 6
