### ISSUE TITLE
Change popup heading Structure > Modify Record Types → Modify Schema / Structure

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#61]
to reflect change in inrterface

**Comment by yangli0516** [comment]
The heading is already "Modify Schema/Structure". Am I looking for the wrong place?
![image](https://user-images.githubusercontent.com/8685304/74000002-a8070b00-49ba-11ea-852d-41a06b091f08.png)

**Comment by ijohnson222** [comment]
then it's already updated

Ian Johnson | Honorary Associate
The University of Sydney
Faculty of Arts and Social Sciences
Rm 316, Old Teachers College A22 | The University of Sydney | NSW | 2006
35, rue des Abbesses, Paris 75018
Au +61 402 389 190 | Fr +33 6 95 34 14 66
E <mailto:firstname.surname@sydney.edu.au> ian.johnson@sydney.edu.au<mailto:ian.johnson@sydney.edu.au>  | HeuristNetwork.org<http://heuristnetwork.org/>  | <http://usyd.academia.edu.au/IanJohnson> sydney.academia.edu/Johnson<http://sydney.academia.edu/Johnson> | sydney.edu.au<http://sydney.edu.au/>
CRICOS 00026A. This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.


________________________________

**Comment by ijohnson222** [comment]
Deprecated by version 6
