### ISSUE TITLE
[Moved to JT] Facet search: Define (map search) button text and button not vertically centred

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#66]
Artem: it is ok for me (Chrome, FF, Edge)
Ian: I get this result on my Surface, external screen, in Firefox, on Ien's laptop, and on her external screen. The word Define runs near the bottom of the button, not in the middle, and the icon is also not vertically centred.

![image](https://user-images.githubusercontent.com/4169217/73693344-2305c280-472a-11ea-8720-cf2dc6db7291.png)

**Comment by yangli0516** [comment]
Couldn't repro the issue. Tried different resolution settings, all looked fine.
![image](https://user-images.githubusercontent.com/8685304/74114661-7d59c400-4bff-11ea-848c-02ba82224884.png)

**Comment by ijohnson222** [comment]
Must be some peculiarity of my account. Consider it solved.

Ian Johnson | Honorary Associate
The University of Sydney
Faculty of Arts and Social Sciences
Rm 316, Old Teachers College A22 | The University of Sydney | NSW | 2006
35, rue des Abbesses, Paris 75018
Au +61 402 389 190 | Fr +33 6 95 34 14 66
E <mailto:firstname.surname@sydney.edu.au> ian.johnson@sydney.edu.au<mailto:ian.johnson@sydney.edu.au>  | HeuristNetwork.org<http://heuristnetwork.org/>  | <http://usyd.academia.edu.au/IanJohnson> sydney.academia.edu/Johnson<http://sydney.academia.edu/Johnson> | sydney.edu.au<http://sydney.edu.au/>
CRICOS 00026A. This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.


________________________________
