### ISSUE TITLE
[Moved to JT] Record edit: trap text field over 64Kb and give explanatory erorr message

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#67]
The message is unhelpful (what is the meaning of  "column 's' at row 1"). Trap the error and give a message to guide the user:

"Sorry, the data for one of your text / memo fields exceeds 64 Kbytes. 

This may not appear to be the case, but UTF formats require 2 or more bytes per visible character and formatted data eg. html or Word, can include a large number of hidden characters - you might only have 10,000 visible characters but still exceed 64K. 

Please split the text into a memo field with repeat values or as separate fields. You could also paste into a plain text editor such as notepad, then copy back to the clipboard to remove all hidden (and visible) formatting." 

![image](https://user-images.githubusercontent.com/4169217/73693584-9a3b5680-472a-11ea-9019-8f7e1a68989a.png)

**Comment by yangli0516** [comment]
@ijohnson222 , it looks like the message has already been changed. However, the text is different from the text specified above. I'm getting this message from the inline page editor. Does the message need to be replaced with the text above?
![image](https://user-images.githubusercontent.com/8685304/74199600-b7d36780-4cb8-11ea-9393-10d0742b0add.png)
