### ISSUE TITLE
Pointer field edit: target record Add <type> button should not show dropdown arrow if only one type

### ISSUE THREAD

**Issue by ijohnson222** [HeuristNetwork/heurist#71]
Up to 9 target record types, individual buttons are shown. These should not have a dopdown arrow. After 9 target types, a single button is shown for all types and this should ahve the dropdown arrow to allow section of different types.

![image](https://user-images.githubusercontent.com/4169217/73696472-7a0e9600-4730-11ea-8c3b-458890a1dad3.png)

**Comment by yangli0516** [comment]
Not sure what the issues are. It looks like the current behavior is the same as described above.

Less than 9 types. No dropdown arrow displayed for each.
![image](https://user-images.githubusercontent.com/8685304/73998427-b868b700-49b5-11ea-94ff-de8ac0ff18c3.png)

More than 9 types. The arrow gets displayed for a single button.
![image](https://user-images.githubusercontent.com/8685304/73998460-d46c5880-49b5-11ea-9b71-76025e5dfd77.png)

**Comment by ijohnson222** [comment]
that seems fixed too

Ian Johnson | Honorary Associate
The University of Sydney
Faculty of Arts and Social Sciences
Rm 316, Old Teachers College A22 | The University of Sydney | NSW | 2006
35, rue des Abbesses, Paris 75018
Au +61 402 389 190 | Fr +33 6 95 34 14 66
E <mailto:firstname.surname@sydney.edu.au> ian.johnson@sydney.edu.au<mailto:ian.johnson@sydney.edu.au>  | HeuristNetwork.org<http://heuristnetwork.org/>  | <http://usyd.academia.edu.au/IanJohnson> sydney.academia.edu/Johnson<http://sydney.academia.edu/Johnson> | sydney.edu.au<http://sydney.edu.au/>
CRICOS 00026A. This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.


________________________________

**Comment by ijohnson222** [comment]
Fixed ages ago
