### ISSUE TITLE
NEW_LIPOSUCTION error

### ISSUE THREAD

**Issue by amadeusgwin** [HeuristNetwork/heurist#76]
When I want to add a record, I get an error that sounds very unfamiliar to everything I have experienced so far in Heurist. Any ideas how I could dissolve the error?
Cannot save details.

System error: execute command denied to user 'heurist_root'@'localhost' for routine 'hdb_amade_domlib.NEW_LIPOSUCTION'

If this error occurs repeatedly, please contact your system administrator or email us (support at HeuristNetwork dot org) and describe the circumstances under which it occurs so that we/they can find a solution
![Bildschirmfoto von 2020-02-10 14-46-54](https://user-images.githubusercontent.com/27728794/74155758-645c0d80-4c15-11ea-87e5-e82a0368c9c6.png)
![Bildschirmfoto von 2020-02-10 14-47-00](https://user-images.githubusercontent.com/27728794/74155770-6920c180-4c15-11ea-9e7d-003d371ce2f9.png)

**Comment by amadeusgwin** [comment]
It was a permission problem on the database

**Comment by ijohnson222** [comment]
Thnaks for letting us know
