### ISSUE TITLE
Some images are broken

### ISSUE THREAD

**Issue by yangli0516** [HeuristNetwork/heurist#77]
It looks like some images from the repo are broken after I cloned the code in a Windows environment. It's probably due to the EOL of the images as I can see the broken ones are ended with LF. These images seem to be broken as well when previewing in GitHub. Need some help to get this solved.
![image](https://user-images.githubusercontent.com/8685304/74203680-924c5b00-4cc4-11ea-8d0f-57bdc11d6e8b.png)
![image](https://user-images.githubusercontent.com/8685304/74203700-a2643a80-4cc4-11ea-9308-fd1ec335869b.png)

**Comment by ijohnson222** [comment]
I believe this was fixed
