### ISSUE TITLE
Bulk file upload works only once

### ISSUE THREAD

**Issue by amadeusgwin** [HeuristNetwork/heurist#84]
If ```import --> upload media files``` is chosen in the main heurist menu, a random number of media files can be uploaded. Repeating the exact same process, an error is displayed ```Folder .... /uploaded_files is not in heurist filestore directory```. Once the directory uploaded_files is deleted manually (no matter how many other mediafile directories were created previously), the bulk upload for media files works again (but only once). Yet, at no time it is possible to index the media files: ```uploaded_files/ is ignored. Folder must be in heurist filestore directory.```

**Comment by amadeusgwin** [comment]
Solved if issue #60 will be solved! If the location of the Filestore is symlinked to another drive, the variable $defaultRootFileUploadPath in heuristConfigIni.php has to be changed to the actual path (not the virtual one). For individual fileuploads (via ``add digital media item``) this problem does not exist. It seems to be a different process, in which the location of the filestore is not checked. Now, this requires however to change the hardcoded filepath in UploadHandler.php (see issue https://github.com/HeuristNetwork/heurist/issues/60 )

**Comment by ijohnson222** [comment]
Transferred to internal job tracking
